# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('desc', models.CharField(max_length=50)),
                ('is_show', models.BooleanField(default=False)),
                ('is_recommend', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('oprate_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='AType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'AType',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='atype',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backweb.AType'),
        ),
    ]
