# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='atype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backweb.AType'),
        ),
    ]
