# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0002_auto_20180813_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.ImageField(default=True, upload_to='upload'),
        ),
    ]
