# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0004_auto_20180813_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.ImageField(default=None, upload_to='upload'),
        ),
    ]
