# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0010_auto_20180814_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='r_u',
        ),
        migrations.AddField(
            model_name='user',
            name='u_r',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backweb.Role'),
        ),
    ]
