# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-18 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0011_auto_20180814_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_read',
            field=models.BooleanField(default=True),
        ),
    ]
