# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0013_auto_20180818_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_learn',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='article',
            name='is_life',
            field=models.BooleanField(default=False),
        ),
    ]
