# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0014_auto_20180821_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_life',
        ),
    ]
