# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0015_remove_article_is_life'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='atype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backweb.AType'),
        ),
    ]
