# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0017_remove_article_atype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_show',
        ),
        migrations.AddField(
            model_name='article',
            name='atype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backweb.AType'),
        ),
    ]
